Dockerfile
Gopkg.lock
Gopkg.toml
arborist/auth_request_json.go
arborist/engine.go
arborist/engine_api.go
arborist/engine_test.go
arborist/server/router_auth.go
vendor/github.com/uc-cdis/go-authutils/authutils/keys.go

Fence now relies on arborist to track the role for data upload; this PR includes some miscellaneous improvements and fixes to support this use case.

feat/upload-role: support for data upload RBAC in fence

---

vendor/github.com/golang/glog/LICENSE
vendor/github.com/golang/glog/README
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go

fix(glog): vendor glog dependency

---

docs/openapi.yaml

Add openapi docs for the arborist API.

feat(docs): add openapi docs

---

README.md

* It took some time for a new Go user to figure out these gotchas.
* Rendered: https://github.com/uc-cdis/arborist/blob/docs/go/README.md

docs(go): README about GOPATH

---

arborist/engine_api.go
arborist/server/router_auth.go
docs/openapi.yaml

- Add `/auth/proxy` endpoint for simple auth request returning error codes (see openAPI docs for details)

feat(resource-check): new auth endpoint

---

arborist/server/errors.go
arborist/server/logging.go
arborist/server/router_auth.go

Fix incorrect error codes returned from `/auth/proxy` endpoint.

fix(proxy): fix code for error responses

---

Makefile
arborist/server.go
arborist/server_test.go
arborist/user.go
migrations/2019-02-18T214320Z_init/delete.sql
migrations/2019-02-18T214320Z_init/up.sql
migrations/README.md

- Add user CRUD endpoints
- Add tests for user endpoints
- `defer` did not have intended effect inside test runs, fixed to have correct behavior
- couple small fixes in db schema, run `make down` and `make up` to reset this version

feat(user-api): work on user endpoints & tests

---

.travis.yml
Makefile
README.md
arborist/server_test.go
docs/openapi.yaml
main.go

- API documentation on users/groups
- README startup guide
- Commandline argument documentation

feat/docs: add API docs for users and groups, improve README and commandline docs

---

arborist/auth.go
migrations/2019-02-18T214320Z_init/up.sql

- Include group policies
- Improved the auth request query

Add group check in auth request

---

arborist/server.go
arborist/user.go
docs/openapi.yaml

- Add method for revoking all user policies (for supporting fence sync)

feat(revoke-all): add endpoint to revoke all policies

---

arborist/resource.go
arborist/response.go
arborist/server.go
arborist/server_test.go
migrations/2019-02-18T214320Z_init/up.sql

- Add tag field to the resources which should be used in cases such as in indexd where we want to maintain a persistent reference to a resource in arborist, whose name & path are potentially mutable.

feat/tag: add unique tag field to resources

---

arborist/resource.go
arborist/server.go
arborist/server_test.go
migrations/2019-02-18T214320Z_init/up.sql

- Simplify the DB schema by not using an internal "root" resource.

fix/no-root: don't use a "root" resource internally

---

docs/openapi.yaml

fixed a wrong reference in Swagger docs

docs(grant-policy): fix docs

---

arborist/policy.go
arborist/server.go
arborist/server_test.go
arborist/sql.go

Support overwriting policies. For fence user sync.
There's also a small bug fix for the group user list test which was behaving non-deterministically. The results are sorted now to fix that.

feat/put-policy: support PUT /policy

---

arborist/server.go

- Fix error handling on auth request

fix(auth): add log

---

arborist/auth.go
arborist/server_test.go
arborist/user.go

- Listing resources for a user or doing an auth resources request includes resources granted as the result of membership in groups.

fix(group-resources): also list resources from groups

---

arborist/server.go

- Consolidate the resource create code together so subresources aren't a special case.

fix(resource-create): consolidate code

---

.travis.yml
README.md

- Add coveralls integration for code coverage analytics.

feat(coveralls): add coveralls to travis.yml

---

docs/openapi.yaml

- Fixed a few bugs in the OpenAPI docs

fix(openapi): fix docs

---

arborist/resource.go
arborist/server.go
arborist/server_test.go
migrations/2019-06-04T173047Z_resource_triggers/delete.sql
migrations/2019-06-04T173047Z_resource_triggers/down.sql
migrations/2019-06-04T173047Z_resource_triggers/up.sql

- Don't alter resource tag on `PUT` request
- Support `?p` flag on `PUT /resource/`

fix(resource-put): don't change tag

---

README.md

- Add some more cute badges to the readme.

feat(badges): add version and travis badges

---

DEVELOP.md
arborist/server.go
migrations/2019-06-04T173047Z_resource_triggers/down.sql
migrations/2019-06-04T173047Z_resource_triggers/up.sql
migrations/up

- Fix resource insert trigger to not make a new tag for existing resources.

fix(resource-put): fix resource insert trigger

---

arborist/auth.go

- Auth resources listings include all the resources below the authorized resources.

fix(auth-resources): include descendant resources

---

arborist/auth.go
arborist/server_test.go

- Fix case for granting policies containing roles with `*`
service/method to anonymous group.

fix(anon-check): fix * case

---

README.md

Add link to swagger docs in the readme

chore(docs)

---

arborist/auth.go
arborist/server.go
arborist/server_test.go
docs/openapi.yaml

- Support `GET /auth/resources` with check token in authorization header

feat(auth-resources-get): support list auth resources with header

---

arborist/auth.go

- Fix bug where arborist would incorrectly return client unauthorized

fix(client-auth): fix bug for client auth

---

arborist/auth.go

- `s/client.name/client.external_client_id`

fix(client-query): fix col name in auth query

---

.travis.yml
Dockerfile
DockerfileAlpine
Makefile
arborist/auth.go
arborist/policy.go
arborist/resource.go
arborist/resource_test.go
arborist/server.go
arborist/server_test.go

- Allow resource paths to contain punctuation.

fix(path-encoding): support punctuation

---

docs/openapi.yaml

fix(openapi): fix indent

---

arborist/group.go

raise error when creating group with nonexistent policies or users

raise error when creating group with nonexistent policies or users

---

README.md
docs/openapi.yaml

chore(rbac): RBAC --> ABAC

---

arborist/auth.go

- client authorization checks when using resource tags should not return `400`'s and now correctly check if client has access

fix(client): correctly check tag for client authorization checks

---

docs/username.md

docs(username)

---

docs/openapi.yaml

- Swagger doc: add "delete user from group" endpoint and fix "list groups" endpoint

add delete user from group endpoint to swagger doc

---

arborist/auth.go

Description about what this pull request does.
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Fix bug where any anonymous user could do any method (read, write, update, delete, etc.) on a resource they were given access to through the anonymous group *if* the service in the role was "*"

Fix anonymous authz bug

---

Dockerfile

fix(may-release): Adopt parent img from quay to avoid pull rate limit errors

fix(may-release): Adopt parent img from quay to avoid pull rate limit errors

---

Gopkg.lock
Gopkg.toml
vendor/github.com/uc-cdis/go-authutils/authutils/validate.go

- Change go-authutils dependency from branch to tag

chore(unbranchify-authutils): bump go-authutils and dep ensure

---

arborist/server.go
arborist/server_test.go
arborist/user.go

Jira Ticket: [PXP-9150](https://ctds-planx.atlassian.net/browse/PXP-9150)
* Improved error handling for Revoke Policy

(PXP-9150): Improve Arborist "delete user policy" error handling

---

.secrets.baseline
README.md
arborist/auth.go
arborist/server.go
docs/openapi.yaml
docs/username.md

Jira Tickets: [PXP-11248](https://ctds-planx.atlassian.net/browse/PXP-11248) and [PXP-11258](https://ctds-planx.atlassian.net/browse/PXP-11258)
Update `/auth/mapping` endpoints docs to describe the behavior as updated in https://github.com/uc-cdis/arborist/pull/159 in #163
- Update `/auth/mapping` endpoints documentation to describe the behavior in more detail.
[PXP-11248]: https://ctds-planx.atlassian.net/browse/PXP-11248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PXP-11258]: https://ctds-planx.atlassian.net/browse/PXP-11258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-11248 PXP-11258 Update /auth/mapping endpoints docs

---

arborist/auth.go

Link to JIRA ticket if there is one: 
- Fix "subquery in FROM must have an alias" error when making an anonymous auth request call with a tag

Fix 'subquery in FROM must have an alias'

---

arborist/auth.go
arborist/resource.go
arborist/response.go
arborist/server.go
arborist/server_test.go
arborist/user.go
docs/username.md

Link to JIRA ticket if there is one: 
- Ensure case insensitive comparison

fix(case): ensure case insensitive comparison
