uc-cdis/arborist

- DEVELOP.md
- Makefile
- README.md
- arborist/auth.go
- arborist/errors.go
- arborist/group.go
- arborist/permission.go
- arborist/policy.go
- arborist/resource.go
- arborist/server.go
- arborist/server_test.go
- arborist/user.go
- Add more tests ~for auth endpoints~. All the tests.
> test/auth: add more tests for auth endpoints

- arborist/resource.go
- arborist/server.go
- arborist/server_test.go
- Fixes a bug causing the subresources to not submit. Submitting resources should work as expected now.
Separates the `Resource` model into a `ResourceIn` (which is the format which should be accepted from user input) and a `ResourceOut` (which is how it should look when returned by the arborist API). The difference is that inputs can specify the entire resource subtree.
> fix(resource): fix resource API for subresources

- DEVELOP.md
- README.md
- arborist/auth.go
- arborist/group.go
- arborist/server.go
- arborist/server_test.go
- arborist/user.go
- migrations/2019-02-18T214320Z_init/up.sql
- Add `anonymous` and `logged-in` groups which can be given their own policies (though they can't contain users). Policies granted to the anonymous group allow to all users, whether or not they have a token, and the ones granted to `logged-in` apply to all users with a JWT.
Also update the README a bit; there was a duplicated section that's removed now.
> feat/anon: add built-in anon & logged-in groups

- arborist/auth.go
- arborist/resource.go
- arborist/server.go
- arborist/server_test.go
- docs/openapi.yaml
Add support for sending multiple auth requests in one call to arborist, where multiple different policies can satisfy different requests sent.
> feat/bulk-auth: add multiple auth request support

- arborist/auth.go
- arborist/server_test.go
Support for `'*'` as service or method in roles.
> feat(star): support `*` for service/method

- arborist/resource.go
- arborist/server.go
- arborist/server_test.go
- docs/openapi.yaml
> PXD-3049: force create resource

- README.md
- arborist/server_test.go
- arborist/user.go
- Include `logged-in` group by default in the list of groups for queried users.
> fix(user-group-list): include logged-in

- arborist/auth.go
- arborist/server.go
- arborist/server_test.go
- Add QS parameter ?tags for /auth/resources which will make it output tags instead of paths.
The /user/{name}/resources endpoint also supports this.
> feat/resource-by-tag: list resources by path or tag

- arborist/resource.go
- arborist/server.go
- arborist/server_test.go
- docs/openapi.yaml
- Add QS param `?p` to `POST /resource` which will make arborist create parent resources for your request if they didn't exist already.
> feat(resource-p): like mkdir -p for resources

- arborist/resource.go
- Fix bug where while using the `?p` flag on resource creation to also
create parents, arborist would not report errors from parent resources
for containing invalid characters.
> fix(p-error): report parent resource invalid

- arborist/policy.go
- arborist/server.go
Note base branch
The desired behavior is to have Arborist have only `PUT /policy/{policyID}` and get the policy id from the URL and ignore the id field in the policy json if it is present. 
This PR adds backwards compatibility for the old version, `PUT /policy`. 
The intention is to remove the old version in 3.0.0. 
add backwards compatibility for PUT /policy/policyid
> fix(put-policy): add bkwd compat and deprecation plan for put policy

- arborist/policy.go
- arborist/resource.go
- arborist/server.go
Previously Arborist's PUT policy endpoint would just delete and (re)create a policy. But this changed the policy's pkey in the db, which breaks links in `[usr, grp, client]_policy`. New PUT policy handler will just delete the relevant entries in the `policy_[resource, role]` tables and make new ones. 
Additionally this PR: 
1. Overwrites policy name in json with policy name from URL _after_ unmarshaling is done, to correctly prefer the name from the URL 
Expected behavior post-Arborist 3.0.0: 
- `PUT /policy` endpoint deprecated and only `PUT /policy/{policyID}` used
- get policy name from url and ignore `id` field from request json if given
Behavior in the meantime (2.x.x): 
- Both `PUT /policy` and `PUT /policy/{policyID}` supported
- If policy name in url, then overwrite policy name in …
> fix(put-policy): update policy without delete-create

- migrations/2019-09-03T155025Z_authz_provider/up.sql
Will do nothing for Arborist 2.3 -> 2.3.1, assuming 2.3 is already taken care of manually.
- Assuming any commons running Arborist < 2.3 was using user sync only as AuthZ provider
> chore(authz): set authz_provider in migration

- arborist/auth.go
the (misleadingly named) 'anonymous' and 'logged-in' user groups' policies should apply to all logged-in users; /auth/mapping already includes this; make /auth/resources do the same
> add anon and logged in policies to /auth/resources

- README.md
Arborist uses the Postgres `ltree` extension module, and the `CREATE EXTENSION` command [must be run by a database superuser](https://www.postgresql.org/docs/9.6/contrib.html).
Much thanks to Qingya for discovering this!!! :pray:
add note to README on requiring db superuser
> add note on requiring db superuser

- arborist/auth.go
- arborist/server.go
- arborist/server_test.go
- arborist/user.go
- docs/openapi.yaml
- docs/username.md
Changes behavior of Arborist endpoints to return the policies of the `anonymous` and `logged-in` groups for requests based on the spec in `docs/username.md`.  Fixes https://github.com/uc-cdis/arborist/issues/113.
Changes behavior of GET, POST `auth/resources`, GET, POST `auth/mapping`, and GET `user/resources` endpoints.
- Arborist endpoints now return the policies of the `anonymous` and `logged-in` groups  based on the spec in `docs/username.md`. 
- Debugged Arborist unit tests and improved test coverage.
- Updated Arborist Swagger API documentation.
> (PXP-4696) Fix anonymous and all_users groups

- arborist/resource.go
The `formatDbPath` function already contains a call to `UnderscoreDecode`. Being executed twice makes the decode wrong in the case where a new replacement case happens. Remove duplicate `UnderscoreDecode` call.
[Slack thread](https://cdis.slack.com/archives/CDDPLU1NU/p1603988739120700?thread_ts=1603856387.104700&cid=CDDPLU1NU)
- Fix edge case causing wrong resource paths to be returned
> Remove duplicate UnderscoreDecode call

- Dockerfile
Address this issue:
```
Could not pull base image: API error (500): toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
> fix(may-release): Adopt parent img from quay to avoid pull rate limit errors

- README.md
Fixed a typo in the main Readme.md file.
> Fix Typo in the Readme.md

- arborist/auth.go
- arborist/server_test.go
The creation of expiring policies and group users was first supported in https://github.com/uc-cdis/arborist/pull/102.
This PR makes changes to the [Auth API](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/uc-cdis/arborist/master/docs/openapi.yaml#/auth) SQL statements to account for the window of time in between when a policy or group user expires and when `jobs/delete_expired_access` runs.
- Account for expired policies and expired group users in Auth API endpoints
> (PXP-8327): Account for expired policies and group users in Auth

- arborist/policy.go
- arborist/role.go
- arborist/server.go
- arborist/server_test.go
- docs/openapi.yaml
Jira Ticket: [PXP-8826](https://ctds-planx.atlassian.net/browse/PXP-8826)
- Support `expand` parameter in `GET /policy` endpoint to get detailed roles instead of only role IDs
- Update `POST /user`, `GET /policy` and `GET /role` endpoints in API docs
> PXP-8826 Support `expand` parameter in `GET /policy` endpoint

- .secrets.baseline
- arborist/server.go
- arborist/server_test.go
- arborist/user.go
- docs/openapi.yaml
Jira Ticket: [PXP-8992](https://ctds-planx.atlassian.net/browse/PXP-8992)
- Add `PATCH /user/{username}` endpoint
> (PXP-8992): PATCH /user/{username}

- arborist/server.go
- arborist/server_test.go
- arborist/token.go
Jira Ticket: [PXP-10113](https://ctds-planx.atlassian.net/browse/PXP-10113)
⚠️ "Client credentials" tokens are not supported by all endpoints, only by the ones needed for the driving use cases
- Support "client credentials" tokens that are not linked to a user in the `/auth/request` and `/auth/proxy` endpoints
> PXP-10113 Support "client credentials" tokens

- .secrets.baseline
- docs/openapi.yaml
relates to https://github.com/uc-cdis/data-portal/pull/1220
- Fix misleading `/auth/proxy` endpoint documentation. The endpoint does not return an `ok` field
> Fix misleading `/auth/proxy` docs

- go.mod
- go.sum
Jira Ticket: [PPS-742](https://ctds-planx.atlassian.net/browse/PPS-742)
Closes #158
```
Before:
$ go list -m all | grep x/net
golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
After:
$ go list -m all | grep x/net
golang.org/x/net v0.10.0
```
- `x/crypto` to version 0.19.0, `x/net` to version 0.10.0
[PPS-742]: https://ctds-planx.atlassian.net/browse/PPS-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PPS-742 Update x/net through x/crypto

- arborist/auth.go
- arborist/server.go
- arborist/server_test.go
Jira Tickets: [PXP-11248](https://ctds-planx.atlassian.net/browse/PXP-11248) and [PXP-11258](https://ctds-planx.atlassian.net/browse/PXP-11258)
Changes from https://github.com/uc-cdis/arborist/pull/159 + unit tests + fix `handleAuthMappingPOST` to work when no body is provided + minor refactoring
- `POST /auth/mapping` supports parsing username and client ID from a token instead of from the request body.
- `POST /auth/mapping` supports tokens produced from a "client_credentials" OIDC flow.
[PXP-11248]: https://ctds-planx.atlassian.net/browse/PXP-11248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PXP-11258]: https://ctds-planx.atlassian.net/browse/PXP-11258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> PXP-11248 PXP-11258 POST /auth/mapping token support

- .secrets.baseline
- arborist/server.go
- arborist/server_test.go
- docs/openapi.yaml
Jira Tickets: [PXP-11248](https://ctds-planx.atlassian.net/browse/PXP-11248) and [PXP-11258](https://ctds-planx.atlassian.net/browse/PXP-11258)
Update to #163
Goes with https://github.com/uc-cdis/guppy/pull/254
Reason for this change: https://github.com/uc-cdis/guppy/pull/254#issuecomment-1983908970
----
Tested in QA - Arborist logs when logic from https://github.com/uc-cdis/guppy/pull/254 kicks in:
- Old or new arborist + old guppy (hits GET endpoint only):
```
- Authenticated call:
INFO: Attempting to get username from jwt...
DEBUG: decoding token: <redacted>
INFO: found username in jwt: <redacted>
"GET /auth/mapping HTTP/1.1" 200
- Anonymous call:
"GET /auth/mapping HTTP/1.1" 200
```
- Old arborist + new guppy (hits POST endpoint, falls back on GET endpoint):
```
- Authenticated call: …
```
> PXP-11248 PXP-11258 "POST /auth/mapping" anonymous support

- arborist/server.go
- `/auth/request` endpoint: add a debug log when an anonymous access request is rejected
> Add a debug log

- arborist/auth.go
- arborist/group.go
- arborist/server.go
- arborist/user.go
Link to JIRA ticket if there is one: [VADC-1233](https://ctds-planx.atlassian.net/browse/VADC-1233)
* case insensitive comparison for usernames
[VADC-1233]: https://ctds-planx.atlassian.net/browse/VADC-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: ignore capitalization for authentication
